region: us-east-1

function_name: safe_image_lambda
handler: aws_image_lambda.get_image
# role: lambda_basic_execution
description: Lambda for serving safe image

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.
aws_access_key_id: AKIAJCLPLPPEBRUTLK5Q
aws_secret_access_key: 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
runtime: python3.6
region: 'eu-central-1'
modules:
  - aws_test
  - aws_image_lambda
main_path: /Users/anastasiia/aws-images-test/
requirements: /Users/anastasiia/aws-images-test/requirements_lambda.txt
# dist_directory: dist
# timeout: 15
# memory_size: 512
